<!doctype html>
<html lang="ms">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="theme-color" content="#FF6565">
    <meta name="description" content="MyOKUcare menghubungkan komuniti OKU dengan pekerjaan, bantuan kebajikan dan sokongan JKM.">
    <title>MyOKUcare — Sokongan Inklusif untuk Semua</title>
    @vite(['resources/css/app.css','resources/js/app.js'])
    <style>
        .welcome{min-height:100vh;background:#fff}.public-nav{position:absolute;inset:0 0 auto;z-index:10;width:min(1180px,calc(100% - 40px));height:82px;margin:auto;display:flex;align-items:center;justify-content:space-between;color:#fff}
        .public-brand{display:flex;align-items:center;gap:11px;text-decoration:none}.public-brand .brand-mark{background:#fff;color:var(--primary-dark);box-shadow:0 10px 28px rgba(112,31,38,.18)}.public-brand strong{display:block;font-size:20px}.public-brand small{display:block;margin-top:3px;color:rgba(255,255,255,.74);font-size:10px}
        .public-actions{display:flex;gap:10px}.public-actions .btn{border-color:rgba(255,255,255,.3);color:#fff;background:rgba(255,255,255,.1);backdrop-filter:blur(10px)}.public-actions .btn-primary{border:0;color:var(--primary-dark);background:#fff}
        .welcome-hero{position:relative;overflow:hidden;min-height:720px;display:grid;align-items:center;color:#fff;background:linear-gradient(135deg,#ff9064 0%,#ff6565 54%,#d9434c 100%)}
        .welcome-hero:before{content:"";position:absolute;width:620px;height:620px;right:-190px;top:-210px;border:95px solid rgba(255,255,255,.07);border-radius:50%}.welcome-hero:after{content:"";position:absolute;width:300px;height:300px;left:-150px;bottom:-130px;border:1px solid rgba(255,255,255,.16);border-radius:50%}
        .hero-inner{position:relative;z-index:1;width:min(1180px,calc(100% - 40px));margin:110px auto 60px;display:grid;grid-template-columns:minmax(0,1fr) minmax(370px,.82fr);gap:70px;align-items:center}
        .hero-tag{display:inline-flex;padding:8px 13px;border:1px solid rgba(255,255,255,.22);border-radius:999px;background:rgba(255,255,255,.1);font-size:11px;font-weight:850;letter-spacing:.06em;text-transform:uppercase}
        .hero-copy h1{max-width:680px;margin:22px 0 20px;font-size:clamp(46px,6vw,76px);line-height:1.02;letter-spacing:-.055em}.hero-copy>p{max-width:610px;margin:0;color:rgba(255,255,255,.82);font-size:17px;line-height:1.75}.hero-buttons{display:flex;gap:12px;margin-top:32px}.hero-buttons .btn{min-height:50px;padding:0 21px}.hero-buttons .primary-light{border:0;color:var(--primary-dark);background:#fff}.hero-buttons .outline-light{border-color:rgba(255,255,255,.34);color:#fff;background:transparent}
        .hero-panel{padding:14px;border:1px solid rgba(255,255,255,.2);border-radius:22px;background:rgba(255,255,255,.13);box-shadow:0 34px 90px rgba(89,29,34,.22);backdrop-filter:blur(12px)}
        .preview{overflow:hidden;border-radius:15px;background:#fff;color:var(--ink)}.preview-top{height:50px;display:flex;align-items:center;gap:7px;padding:0 16px;border-bottom:1px solid var(--line);background:#fafbfc}.dot{width:8px;height:8px;border-radius:50%;background:#d9dce3}
        .preview-body{padding:18px}.preview-greeting{height:13px;width:43%;margin-bottom:18px;border-radius:99px;background:#e9ebef}.preview-metrics{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.preview-card{height:86px;padding:13px;border:1px solid var(--line);border-radius:10px}.preview-card:before{content:"";display:block;width:30px;height:30px;margin-bottom:10px;border-radius:9px;background:var(--primary-soft)}.preview-card:after{content:"";display:block;width:56%;height:8px;border-radius:99px;background:#dfe2e8}.preview-chart{height:155px;display:flex;align-items:flex-end;gap:14px;margin-top:12px;padding:25px 18px 12px;border:1px solid var(--line);border-radius:10px;background:repeating-linear-gradient(to bottom,#f2f3f6 0,#f2f3f6 1px,transparent 1px,transparent 38px)}.preview-chart i{flex:1;border-radius:6px 6px 2px 2px;background:linear-gradient(to top,var(--primary),var(--primary-2))}
        .welcome-section{width:min(1120px,calc(100% - 40px));margin:0 auto;padding:88px 0}.section-title{max-width:670px;margin:0 auto 42px;text-align:center}.section-title .eyebrow{margin-bottom:10px}.section-title h2{margin:0 0 14px;font-size:clamp(30px,4vw,44px);letter-spacing:-.04em}.section-title p{margin:0;color:var(--muted);line-height:1.7}
        .feature-cards{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.feature-card{padding:28px;border:1px solid var(--line);border-radius:15px;background:#fff}.feature-symbol{width:50px;height:50px;display:grid;place-items:center;margin-bottom:20px;border-radius:13px;color:var(--primary-dark);background:var(--primary-soft);font-size:20px;font-weight:900}.feature-card h3{margin:0 0 10px;font-size:17px}.feature-card p{margin:0;color:var(--muted);font-size:13px;line-height:1.7}
        .welcome-cta{width:min(1120px,calc(100% - 40px));margin:0 auto 70px;padding:46px;display:flex;align-items:center;justify-content:space-between;gap:28px;border-radius:20px;color:#fff;background:linear-gradient(135deg,var(--primary-2),var(--primary))}.welcome-cta h2{margin:0 0 8px;font-size:30px}.welcome-cta p{margin:0;color:rgba(255,255,255,.8)}.welcome-cta .btn{color:var(--primary-dark);background:#fff}
        .public-footer{padding:25px;text-align:center;border-top:1px solid var(--line);color:var(--muted);font-size:12px}
        @media(max-width:900px){.hero-inner{grid-template-columns:1fr;gap:42px}.welcome-hero{min-height:auto}.hero-panel{max-width:620px}.feature-cards{grid-template-columns:1fr}.welcome-cta{align-items:flex-start;flex-direction:column}}
        @media(max-width:600px){.public-nav{height:70px}.public-brand small,.public-actions .login-link{display:none}.public-actions .btn{min-height:40px;padding:0 12px}.hero-inner{margin-top:110px}.hero-copy h1{font-size:43px}.hero-copy>p{font-size:14px}.hero-buttons{flex-direction:column}.hero-buttons .btn{width:100%}.preview-metrics{grid-template-columns:1fr}.preview-card:nth-child(n+2){display:none}.welcome-section{padding:60px 0}.welcome-cta{padding:28px}}
    </style>
</head>
<body>
<div class="welcome">
    <header class="public-nav"><a class="public-brand" href="{{ route('welcome') }}"><span class="brand-mark">M</span><span><strong>MyOKUcare</strong><small>Sistem Sokongan OKU</small></span></a><nav class="public-actions"><a class="btn login-link" href="{{ route('login') }}">Log Masuk</a><a class="btn btn-primary" href="{{ route('register') }}">Daftar Akaun</a></nav></header>
    <main>
        <section class="welcome-hero"><div class="hero-inner"><div class="hero-copy"><span class="hero-tag">Komuniti · Pekerjaan · Kebajikan</span><h1>Sokongan inklusif untuk kehidupan yang lebih baik.</h1><p>MyOKUcare menyatukan maklumat OKU, peluang pekerjaan yang sesuai dan pengurusan bantuan kebajikan dalam satu sistem yang mudah dicapai.</p><div class="hero-buttons"><a class="btn primary-light" href="{{ route('register') }}">Mulakan Pendaftaran</a><a class="btn outline-light" href="{{ route('login') }}">Saya Sudah Ada Akaun</a></div></div><div class="hero-panel" aria-label="Pratonton dashboard MyOKUcare"><div class="preview"><div class="preview-top"><span class="dot"></span><span class="dot"></span><span class="dot"></span></div><div class="preview-body"><div class="preview-greeting"></div><div class="preview-metrics"><div class="preview-card"></div><div class="preview-card"></div><div class="preview-card"></div></div><div class="preview-chart"><i style="height:42%"></i><i style="height:68%"></i><i style="height:51%"></i><i style="height:82%"></i><i style="height:62%"></i></div></div></div></div></div></section>
        <section class="welcome-section"><div class="section-title"><p class="eyebrow">Apa yang MyOKUcare sediakan</p><h2>Satu platform untuk setiap langkah sokongan</h2><p>Direka untuk komuniti OKU, ahli keluarga, majikan dan pegawai JKM dengan paparan khusus mengikut peranan.</p></div><div class="feature-cards"><article class="feature-card"><span class="feature-symbol">◉</span><h3>Profil dan Rekod OKU</h3><p>Maklumat individu disimpan secara tersusun untuk memudahkan pengurusan dan tindakan susulan.</p></article><article class="feature-card"><span class="feature-symbol">◆</span><h3>Pekerjaan Inklusif</h3><p>Temui peluang pekerjaan yang dipadankan dengan kategori dan keperluan individu.</p></article><article class="feature-card"><span class="feature-symbol">♡</span><h3>Sokongan Kebajikan</h3><p>Pantau permohonan, proses semakan dan bantuan kebajikan melalui satu aliran yang jelas.</p></article></div></section>
        <section class="welcome-cta"><div><h2>Sedia untuk menggunakan MyOKUcare?</h2><p>Daftar akaun baharu atau log masuk menggunakan e-mel anda.</p></div><a class="btn" href="{{ route('register') }}">Daftar Sekarang</a></section>
    </main>
    <footer class="public-footer">© {{ date('Y') }} MyOKUcare. Sistem sokongan komuniti OKU.</footer>
</div>
</body>
</html>
