@extends('layout',['title'=>'Dashboard Majikan'])
@section('content')
<div class="page-head"><div><p class="eyebrow">{{ __('ui.portal_majikan.1d3358f2') }}</p><h2>{{ $employer?->company_name ?? 'Selamat datang, Majikan' }}</h2><p>{{ __('ui.pantau_jawatan_permohonan_calon_dan_hasil_pengambilan.84cfb4de') }}</p></div><a class="btn btn-primary" href="{{ route('jobs.index') }}">{{ __('ui.lihat_peluang_kerja.bf6bcf31') }}</a></div>
@php $metrics=[['Jumlah Jawatan',$totalJobs,'◆'],['Jawatan Aktif',$activeJobs,'✓'],['Jumlah Permohonan',$applications,'◎'],['Calon Diambil',$hired,'★']]; @endphp
<section class="metric-grid">@foreach($metrics as [$label,$value,$icon])<article class="metric-card"><div class="metric-top"><span class="metric-icon">{{ $icon }}</span><span class="metric-change">{{ __('ui.syarikat_anda.16a20c1d') }}</span></div><span>{{ $label }}</span><strong>{{ number_format($value) }}</strong></article>@endforeach</section>
<section class="dashboard-grid">
    <article class="panel"><div class="panel-head"><div><h3>{{ __('ui.jawatan_terkini.1313d970') }}</h3><p>{{ __('ui.prestasi_iklan_pekerjaan_syarikat_anda.64ad110c') }}</p></div></div><div class="activity-list">@forelse($jobs as $job)<div class="activity-row"><span class="metric-icon">◆</span><div><strong>{{ $job->title }}</strong><span>{{ $job->location }} · {{ $job->employment_type }}</span></div><b>{{ $job->job_interests_count }} calon</b></div>@empty<div class="empty">{{ $employer ? 'Belum ada jawatan diterbitkan.' : 'Akaun ini belum dipautkan kepada profil majikan.' }}</div>@endforelse</div></article>
    <aside class="panel"><div class="panel-head"><div><h3>{{ __('ui.tindakan_majikan.7da01e27') }}</h3><p>{{ __('ui.urus_operasi_pengambilan.24b1a5fe') }}</p></div></div><div class="quick-list"><a class="quick-link" href="{{ route('jobs.index') }}"><span class="metric-icon">◆</span><span><strong>{{ __('ui.senarai_jawatan.17b4801e') }}</strong><span>{{ __('ui.semak_jawatan_tersedia.cabdb4b0') }}</span></span></a><a class="quick-link" href="{{ route('employers.index') }}"><span class="metric-icon">▣</span><span><strong>{{ __('ui.profil_syarikat.411a9e7d') }}</strong><span>{{ __('ui.lihat_maklumat_majikan.168ed46d') }}</span></span></a></div></aside>
</section>
@endsection
