@extends('layout',['title'=>__('export.title')])
@section('content')
<div class="page-head"><div><p class="eyebrow">{{ __('nav.reports') }}</p><h2>{{ __('export.title') }}</h2><p>{{ __('export.description') }}</p></div></div>
<form class="panel form-section" method="post" action="{{ route('exports.store') }}">@csrf<div class="form-grid">
<div class="form-group"><label>{{ __('export.report_type') }}</label><select class="select" name="report_type">@foreach($types as $type)<option value="{{ $type }}">{{ __('export.report.'.strtolower($type)) }}</option>@endforeach</select></div>
<div class="form-group"><label>{{ __('export.format') }}</label><select class="select" name="format">@foreach($formats as $format)<option>{{ $format }}</option>@endforeach</select></div>
<div class="form-group"><label>{{ __('export.language') }}</label><select class="select" name="language"><option value="BM">{{ __('ui.bahasa_melayu.3d6241c6') }}</option><option value="EN">{{ __('ui.english.649df08a') }}</option><option value="ZH_CN">中文（简体）</option></select></div>
<div class="form-group"><label>{{ __('export.content_mode') }}</label><select class="select" name="content_mode"><option value="TRANSLATED">{{ __('export.translated') }}</option><option value="ORIGINAL">{{ __('export.original') }}</option><option value="DUAL">{{ __('export.dual') }}</option></select></div>
<div class="form-group full"><label>{{ __('export.purpose') }}</label><select class="select" name="purpose" required>@foreach($purposes as $purpose)<option>{{ $purpose }}</option>@endforeach</select></div>
</div><div class="form-actions"><button class="btn btn-primary" type="submit">{{ __('export.generate') }}</button></div></form>
<section class="panel"><div class="table-wrap"><table class="data-table mobile-card-table"><thead><tr><th>{{ __('ui.rujukan.f2903512') }}</th><th>{{ __('ui.jenis.fabb2b5c') }}</th><th>{{ __('ui.format.041a5dec') }}</th><th>{{ __('ui.rekod.2c032ea6') }}</th><th>{{ __('ui.status.bae7d5be') }}</th><th>{{ __('ui.tamat.ca30d178') }}</th><th></th></tr></thead><tbody>@forelse($exports as $export)<tr><td data-label="{{ __('ui.rujukan.f2903512') }}">{{ $export->id }}</td><td data-label="{{ __('ui.jenis.fabb2b5c') }}">{{ $export->export_type }}</td><td data-label="{{ __('ui.format.041a5dec') }}">{{ $export->format }}</td><td data-label="{{ __('ui.rekod.2c032ea6') }}">{{ $export->record_count }}</td><td data-label="{{ __('ui.status.bae7d5be') }}">{{ $export->status }}</td><td data-label="{{ __('ui.tamat.ca30d178') }}">{{ $export->expires_at->format('d/m/Y H:i') }}</td><td data-label="{{ __('ui.tindakan.4c20e744') }}">@if($export->status==='READY'&&!$export->expires_at->isPast())<a href="{{ URL::temporarySignedRoute('exports.download',$export->expires_at,['export'=>$export]) }}">Muat turun</a>@endif</td></tr>@empty<tr><td colspan="7" class="empty">{{ __('ui.tiada_eksport_dijana.9b56d62c') }}</td></tr>@endforelse</tbody></table></div></section>{{ $exports->links() }}
@endsection
