@extends('layout',['title'=>'Rekod Dipadam'])
@section('content')
<div class="page-head"><div><p class="eyebrow">{{ __('ui.pentadbiran_data.822c3d44') }}</p><h2>{{ __('ui.rekod_dipadam.215aef4e') }}</h2><p>{{ __('ui.pulihkan_rekod_atau_lakukan_pemadaman_kekal_dengan.73cf7bbe') }}</p></div></div>
@foreach(['Majikan'=>$employers,'Pengguna OKU'=>$okus] as $title=>$records)
<section class="panel" style="margin-bottom:18px"><div class="panel-head"><h3>{{ $title }}</h3></div><div class="table-wrap"><table class="data-table mobile-card-table"><thead><tr><th>{{ __('ui.nama.79d12c10') }}</th><th>{{ __('ui.sebab.f0949952') }}</th><th>{{ __('ui.tarikh.bb81283e') }}</th><th>{{ __('ui.tindakan.4c20e744') }}</th></tr></thead><tbody>@forelse($records as $record)
@php($isEmployer=$record instanceof \App\Models\Employer)
<tr><td data-label="{{ __('ui.nama.79d12c10') }}">{{ $record->company_name ?? $record->name }}</td><td data-label="{{ __('ui.sebab.f0949952') }}">{{ $record->deletion_reason }}<small>{{ $record->deletion_notes }}</small></td><td data-label="{{ __('ui.tarikh.bb81283e') }}">{{ $record->deleted_at?->format('d/m/Y H:i') }}</td><td data-label="{{ __('ui.tindakan.4c20e744') }}"><div class="page-actions">
@if(app(\App\Services\PermissionService::class)->allows(auth()->user(),'record.restore'))<form method="post" action="{{ $isEmployer?route('deleted-records.employers.restore',$record->id):route('deleted-records.okus.restore',$record->id) }}" onsubmit="return confirm('Restore record? This record will become active and accessible again.')">@csrf<input type="hidden" name="restore_reason" value="Semakan pentadbir"><button class="btn" type="submit">{{ __('ui.pulihkan.a3db5be7') }}</button></form>@endif
@if(app(\App\Services\PermissionService::class)->allows(auth()->user(),'record.permanent_delete'))<details><summary class="btn btn-danger">{{ __('ui.padam_kekal.f407bb6f') }}</summary><form method="post" action="{{ $isEmployer?route('deleted-records.employers.permanent',$record->id):route('deleted-records.okus.permanent',$record->id) }}">@csrf @method('DELETE')<p>{{ __('ui.tindakan_ini_tidak_boleh_dibatalkan_rekod_berkaitan.0315aaf7') }}</p><label for="delete-reason-{{ $record->id }}">{{ __('ui.sebab.f0949952') }}</label><input class="field" id="delete-reason-{{ $record->id }}" name="reason" required><label for="delete-confirmation-{{ $record->id }}">Taip PERMANENTLY DELETE untuk mengesahkan</label><input class="field" id="delete-confirmation-{{ $record->id }}" name="confirmation_text" required><label for="delete-password-{{ $record->id }}">{{ __('ui.kata_laluan_semasa.16f381e5') }}</label><input class="field" id="delete-password-{{ $record->id }}" name="password" type="password" autocomplete="current-password" required><button class="btn btn-danger" type="submit">{{ __('ui.permanently_delete.2eea1fa8') }}</button></form></details>@endif
</div></td></tr>@empty<tr><td colspan="4" class="empty">{{ __('ui.tiada_rekod_dipadam.ce1fd8f2') }}</td></tr>@endforelse</tbody></table></div></section>
@endforeach
<style>.btn-danger{background:#a61b29!important;color:#fff!important}details>form{position:absolute;z-index:3;background:white;padding:18px;border:1px solid #ddd;border-radius:12px;box-shadow:0 16px 40px #0003;width:min(360px,80vw)}details>form .field{margin-bottom:8px}</style>
@endsection
