-- MyOKUcare complete MySQL 8+/MariaDB 10.6+ database
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS=0;
CREATE DATABASE IF NOT EXISTS myokucare CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE myokucare;
DROP TABLE IF EXISTS job_interests,review_schedules,welfare_applications,oku_employments,oku_category_matches,jobs,employers,okus,personal_access_tokens,password_reset_tokens,sessions,queue_jobs,job_batches,failed_jobs,cache_locks,cache,users;
CREATE TABLE users (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,email VARCHAR(255) NOT NULL UNIQUE,email_verified_at TIMESTAMP NULL,password VARCHAR(255) NOT NULL,role ENUM('super_admin','jkm_officer','employer','oku_user','family_member','viewer') NOT NULL DEFAULT 'viewer',employer_id BIGINT UNSIGNED NULL,oku_id BIGINT UNSIGNED NULL,is_active BOOLEAN NOT NULL DEFAULT TRUE,last_login_at TIMESTAMP NULL,remember_token VARCHAR(100),created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,KEY(role),KEY(employer_id),KEY(oku_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE password_reset_tokens (email VARCHAR(255) PRIMARY KEY,token VARCHAR(255) NOT NULL,created_at TIMESTAMP NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE sessions (id VARCHAR(255) PRIMARY KEY,user_id BIGINT UNSIGNED NULL,ip_address VARCHAR(45),user_agent TEXT,payload LONGTEXT NOT NULL,last_activity INT NOT NULL,KEY(user_id),KEY(last_activity)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE cache (`key` VARCHAR(255) PRIMARY KEY,`value` MEDIUMTEXT NOT NULL,expiration INT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE cache_locks (`key` VARCHAR(255) PRIMARY KEY,owner VARCHAR(255) NOT NULL,expiration INT NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE queue_jobs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,queue VARCHAR(255) NOT NULL,payload LONGTEXT NOT NULL,attempts TINYINT UNSIGNED NOT NULL,reserved_at INT UNSIGNED NULL,available_at INT UNSIGNED NOT NULL,created_at INT UNSIGNED NOT NULL,KEY(queue)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE job_batches (id VARCHAR(255) PRIMARY KEY,name VARCHAR(255) NOT NULL,total_jobs INT NOT NULL,pending_jobs INT NOT NULL,failed_jobs INT NOT NULL,failed_job_ids LONGTEXT NOT NULL,options MEDIUMTEXT NULL,cancelled_at INT NULL,created_at INT NOT NULL,finished_at INT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE failed_jobs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,uuid VARCHAR(255) NOT NULL UNIQUE,connection TEXT NOT NULL,queue TEXT NOT NULL,payload LONGTEXT NOT NULL,exception LONGTEXT NOT NULL,failed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE personal_access_tokens (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tokenable_type VARCHAR(255) NOT NULL,tokenable_id BIGINT UNSIGNED NOT NULL,name TEXT NOT NULL,token VARCHAR(64) NOT NULL UNIQUE,abilities TEXT,last_used_at TIMESTAMP NULL,expires_at TIMESTAMP NULL,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,KEY(tokenable_type,tokenable_id),KEY(expires_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE okus (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,name VARCHAR(255) NOT NULL,ic_number VARCHAR(20) NOT NULL UNIQUE,gender ENUM('Lelaki','Perempuan') NOT NULL,age TINYINT UNSIGNED NOT NULL,marital_status ENUM('Berkahwin','Bujang','Duda','Janda') NOT NULL,address TEXT NOT NULL,education_level VARCHAR(100) NOT NULL,oku_card_number VARCHAR(50) NOT NULL UNIQUE,oku_category ENUM('Fizikal','Pendengaran','Mental','Pembelajaran','Penglihatan') NOT NULL,employment_status ENUM('Bekerja','Tidak Bekerja','Sendiri') NOT NULL DEFAULT 'Tidak Bekerja',phone_number VARCHAR(20),email VARCHAR(255),has_smartphone BOOLEAN NOT NULL DEFAULT TRUE,has_internet BOOLEAN NOT NULL DEFAULT FALSE,emergency_contact_name VARCHAR(255),emergency_contact_phone VARCHAR(20),profile_photo_path VARCHAR(2048),is_active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,deleted_at TIMESTAMP NULL,KEY(oku_category,employment_status),KEY(age)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE employers (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,company_name VARCHAR(255) NOT NULL,registration_number VARCHAR(50) NOT NULL UNIQUE,address TEXT NOT NULL,industry_sector VARCHAR(100) NOT NULL,contact_person VARCHAR(255) NOT NULL,phone_number VARCHAR(20) NOT NULL,email VARCHAR(255) NOT NULL UNIQUE,website VARCHAR(255),company_description TEXT,number_of_employees INT UNSIGNED,has_oku_quota BOOLEAN NOT NULL DEFAULT FALSE,is_active BOOLEAN NOT NULL DEFAULT TRUE,logo_path VARCHAR(2048),created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,deleted_at TIMESTAMP NULL,KEY(industry_sector,is_active)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE jobs (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,employer_id BIGINT UNSIGNED NOT NULL,title VARCHAR(255) NOT NULL,description TEXT NOT NULL,requirements TEXT NOT NULL,responsibilities TEXT,oku_category_suitable ENUM('Fizikal','Pendengaran','Mental','Pembelajaran','Penglihatan','Semua') NOT NULL,salary_min DECIMAL(10,2) NOT NULL,salary_max DECIMAL(10,2),location VARCHAR(255) NOT NULL,working_hours VARCHAR(100),employment_type ENUM('Sepenuh Masa','Separuh Masa','Kontrak','Sementara') NOT NULL DEFAULT 'Sepenuh Masa',application_deadline DATE,is_active BOOLEAN NOT NULL DEFAULT TRUE,views_count INT UNSIGNED NOT NULL DEFAULT 0,applications_count INT UNSIGNED NOT NULL DEFAULT 0,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,deleted_at TIMESTAMP NULL,KEY(employer_id),KEY(oku_category_suitable,is_active),KEY(location,application_deadline),CONSTRAINT jobs_employer_fk FOREIGN KEY(employer_id) REFERENCES employers(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE oku_employments (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,oku_id BIGINT UNSIGNED NOT NULL,job_id BIGINT UNSIGNED NOT NULL,start_date DATE NOT NULL,end_date DATE,status ENUM('Active','Resigned','Terminated','Completed') NOT NULL DEFAULT 'Active',salary DECIMAL(10,2),notes TEXT,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,KEY(oku_id),KEY(job_id),KEY(status,start_date,end_date),FOREIGN KEY(oku_id) REFERENCES okus(id) ON DELETE CASCADE,FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE welfare_applications (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,oku_id BIGINT UNSIGNED NOT NULL,application_type VARCHAR(100) NOT NULL,status ENUM('Pending','Under Review','Approved','Rejected') NOT NULL DEFAULT 'Pending',application_date DATE NOT NULL,review_date DATE,notes TEXT,rejection_reason TEXT,reviewed_by BIGINT UNSIGNED,next_review_date DATE,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,KEY(oku_id),KEY(reviewed_by),KEY(status,application_date),KEY(review_date),FOREIGN KEY(oku_id) REFERENCES okus(id) ON DELETE CASCADE,FOREIGN KEY(reviewed_by) REFERENCES users(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE review_schedules (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,welfare_application_id BIGINT UNSIGNED NOT NULL,scheduled_date DATE NOT NULL,status ENUM('Pending','Completed','Cancelled','Rescheduled') NOT NULL DEFAULT 'Pending',notes TEXT,completed_date DATE,review_findings TEXT,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,KEY(welfare_application_id),KEY(status,scheduled_date),FOREIGN KEY(welfare_application_id) REFERENCES welfare_applications(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE job_interests (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,oku_id BIGINT UNSIGNED NOT NULL,job_id BIGINT UNSIGNED NOT NULL,status ENUM('Interested','Applied','Shortlisted','Interviewed','Hired','Rejected') NOT NULL DEFAULT 'Interested',notes TEXT,application_date DATE,interview_date DATE,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,UNIQUE(oku_id,job_id),KEY(job_id),KEY(status),FOREIGN KEY(oku_id) REFERENCES okus(id) ON DELETE CASCADE,FOREIGN KEY(job_id) REFERENCES jobs(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE oku_category_matches (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,oku_category VARCHAR(50) NOT NULL,job_category VARCHAR(100) NOT NULL,match_score TINYINT UNSIGNED NOT NULL DEFAULT 50,notes TEXT,created_at TIMESTAMP NULL,updated_at TIMESTAMP NULL,UNIQUE(oku_category,job_category)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE users ADD CONSTRAINT users_employer_fk FOREIGN KEY(employer_id) REFERENCES employers(id) ON DELETE SET NULL,ADD CONSTRAINT users_oku_fk FOREIGN KEY(oku_id) REFERENCES okus(id) ON DELETE SET NULL;
INSERT INTO users (name,email,email_verified_at,password,role,is_active,created_at,updated_at) VALUES
('Super Admin','admin@myokucare.test',NOW(),'$2y$12$R/CdOFoTpbtedUv3IaIQWeqAMfvPQH/SCEO/zsP7QTKcglZwIJ32K','super_admin',1,NOW(),NOW()),
('Pegawai JKM','pegawai@myokucare.test',NOW(),'$2y$12$R/CdOFoTpbtedUv3IaIQWeqAMfvPQH/SCEO/zsP7QTKcglZwIJ32K','jkm_officer',1,NOW(),NOW()),
('Wakil Majikan','majikan@myokucare.test',NOW(),'$2y$12$R/CdOFoTpbtedUv3IaIQWeqAMfvPQH/SCEO/zsP7QTKcglZwIJ32K','employer',1,NOW(),NOW()),
('Pengguna OKU','oku@myokucare.test',NOW(),'$2y$12$R/CdOFoTpbtedUv3IaIQWeqAMfvPQH/SCEO/zsP7QTKcglZwIJ32K','oku_user',1,NOW(),NOW()),
('Ahli Keluarga','keluarga@myokucare.test',NOW(),'$2y$12$R/CdOFoTpbtedUv3IaIQWeqAMfvPQH/SCEO/zsP7QTKcglZwIJ32K','family_member',1,NOW(),NOW()),
('Pegawai Pemerhati','viewer@myokucare.test',NOW(),'$2y$12$R/CdOFoTpbtedUv3IaIQWeqAMfvPQH/SCEO/zsP7QTKcglZwIJ32K','viewer',1,NOW(),NOW());
SET FOREIGN_KEY_CHECKS=1;
