@extends('layout',['title'=>$job->exists?'Kemaskini Jawatan':'Tambah Jawatan'])
@section('content')
@php $value=fn($field,$default='')=>old($field,$job->exists?$job->{$field}:$default); @endphp
<div class="page-head"><div><p class="eyebrow">{{ __('ui.pekerjaan_inklusif.c138085d') }}</p><h2>{{ $job->exists?'Kemaskini Peluang Kerja':'Tambah Peluang Kerja' }}</h2><p>{{ __('ui.terbitkan_jawatan_dengan_keperluan_dan_kesesuaian_oku.ec9943a0') }}</p></div><a class="btn" href="{{ route('jobs.index') }}">{{ __('ui.kembali.0b8ff91a') }}</a></div>
@if($errors->any())<div class="error form-error-summary" role="alert"><strong>{{ __('ui.sila_semak_maklumat_berikut.f29d1fe9') }}</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form class="oku-record-form" method="post" action="{{ $job->exists?route('jobs.update',$job):route('jobs.store') }}">@csrf @if($job->exists)@method('PUT')@endif
<section class="panel form-section"><div class="form-section-head"><span>01</span><div><h3>{{ __('ui.maklumat_jawatan.c8cd08b3') }}</h3><p>{{ __('ui.maklumat_asas_iklan_dan_organisasi.f3efdeb5') }}</p></div></div><div class="form-grid">
<div class="form-group"><label for="employer_id">{{ __('ui.majikan.73adc28e') }} <span class="required-mark">*</span></label><select class="select" id="employer_id" name="employer_id" required><option value="">{{ __('ui.pilih_majikan.b0d41b1f') }}</option>@foreach($employers as $employer)<option value="{{ $employer->id }}" @selected((string)$value('employer_id')===(string)$employer->id)>{{ $employer->company_name }}</option>@endforeach</select>@error('employer_id')<span class="field-error">{{ $message }}</span>@enderror</div>
<div class="form-group"><label for="title">{{ __('ui.nama_jawatan.bfe039a3') }} <span class="required-mark">*</span></label><input class="field" id="title" name="title" value="{{ $value('title') }}" required>@error('title')<span class="field-error">{{ $message }}</span>@enderror</div>
<div class="form-group"><label for="location">{{ __('ui.lokasi.7e1ab5d9') }} <span class="required-mark">*</span></label><input class="field" id="location" name="location" value="{{ $value('location') }}" required></div>
<div class="form-group"><label for="employment_type">{{ __('ui.jenis_pekerjaan.530078bd') }} <span class="required-mark">*</span></label><select class="select" id="employment_type" name="employment_type" required>@foreach(['Sepenuh Masa','Separuh Masa','Kontrak','Sementara'] as $option)<option @selected($value('employment_type','Sepenuh Masa')===$option)>{{ $option }}</option>@endforeach</select></div>
<div class="form-group full"><label for="description">{{ __('ui.penerangan_jawatan.d5330a50') }} <span class="required-mark">*</span></label><textarea class="textarea" id="description" name="description" rows="4" required>{{ $value('description') }}</textarea></div>
</div></section>
<section class="panel form-section"><div class="form-section-head"><span>02</span><div><h3>{{ __('ui.kesesuaian_keperluan.b907b0ac') }}</h3><p>{{ __('ui.nyatakan_kategori_oku_dan_skop_kerja_dengan.72a8709c') }}</p></div></div><div class="form-grid">
<div class="form-group"><label for="oku_category_suitable">{{ __('ui.kategori_oku_sesuai.31b37c1b') }} <span class="required-mark">*</span></label><select class="select" id="oku_category_suitable" name="oku_category_suitable" required>@foreach(['Semua','Fizikal','Pendengaran','Mental','Pembelajaran','Penglihatan'] as $option)<option @selected($value('oku_category_suitable','Semua')===$option)>{{ $option }}</option>@endforeach</select></div>
<div class="form-group"><label for="working_hours">{{ __('ui.waktu_bekerja.56965909') }}</label><input class="field" id="working_hours" name="working_hours" value="{{ $value('working_hours') }}"></div>
<div class="form-group full"><label for="requirements">{{ __('ui.keperluan_jawatan.26352513') }} <span class="required-mark">*</span></label><textarea class="textarea" id="requirements" name="requirements" rows="4" required>{{ $value('requirements') }}</textarea></div>
<div class="form-group full"><label for="responsibilities">{{ __('ui.tanggungjawab.9a45d2bc') }}</label><textarea class="textarea" id="responsibilities" name="responsibilities" rows="4">{{ $value('responsibilities') }}</textarea></div>
</div></section>
<section class="panel form-section"><div class="form-section-head"><span>03</span><div><h3>{{ __('ui.gaji_penerbitan.d52b087c') }}</h3><p>{{ __('ui.tetapkan_julat_gaji_dan_tempoh_permohonan.96639a6b') }}</p></div></div><div class="form-grid">
<div class="form-group"><label for="salary_min">{{ __('ui.gaji_minimum_rm.326b59f8') }} <span class="required-mark">*</span></label><input class="field" id="salary_min" name="salary_min" type="number" min="0" step="50" value="{{ $value('salary_min') }}" required></div>
<div class="form-group"><label for="salary_max">{{ __('ui.gaji_maksimum_rm.2e4c35fc') }}</label><input class="field" id="salary_max" name="salary_max" type="number" min="0" step="50" value="{{ $value('salary_max') }}"></div>
<div class="form-group"><label for="application_deadline">{{ __('ui.tarikh_tutup.ee57a073') }}</label><input class="field" id="application_deadline" name="application_deadline" type="date" value="{{ old('application_deadline',$job->application_deadline?->format('Y-m-d')) }}"></div>
<fieldset class="form-group choice-group"><legend>{{ __('ui.status_iklan.59086a47') }}</legend><label class="check-option"><input type="hidden" name="is_active" value="0"><input name="is_active" type="checkbox" value="1" @checked((bool)$value('is_active',true))><span>{{ __('ui.iklan_aktif.f358f164') }}</span></label></fieldset>
</div></section>
<div class="form-actions"><a class="btn" href="{{ route('jobs.index') }}">{{ __('ui.batal.1433539c') }}</a><button class="btn btn-primary" type="submit">{{ $job->exists?'Simpan Perubahan':'Terbitkan Jawatan' }}</button></div>
</form>
@endsection
