<?php

return [
    'state' => 'Terengganu',
    'district' => 'Besut',
    'states' => [
        'Johor',
        'Kedah',
        'Kelantan',
        'Melaka',
        'Negeri Sembilan',
        'Pahang',
        'Perak',
        'Perlis',
        'Pulau Pinang',
        'Sabah',
        'Sarawak',
        'Selangor',
        'Terengganu',
        'Wilayah Persekutuan Kuala Lumpur',
        'Wilayah Persekutuan Labuan',
        'Wilayah Persekutuan Putrajaya',
    ],
    'mukims' => [
        'Bukit Kenak',
        'Bukit Puteri',
        'Hulu Besut',
        'Jabi',
        'Kampung Raja',
        'Keluang',
        'Kerandang',
        'Kuala Besut',
        'Kubang Bemban',
        'Lubuk Kawah',
        'Pasir Akar',
        'Pelagat',
        'Pengkalan Nangka',
        'Tembila',
        'Tenang',
    ],
];
